### PR TITLE
Fixed mangling of markdown-produced HTML next to top-level text nodes…

### LINKED ISSUE #149: mangled html elements
The following `<label>**Note with bold** nnnn</label>` currently gets transformed into:

```html
<span lang="" class="question-label active"><strong>Note with bold<p> nnnn</p></strong></span>
```

instead of what is expected:
```html
<span lang="" class="question-label active"><strong>Note with bold</strong> nnnn</span>
```

[Bold_issue.xml.txt](https://github.com/enketo/enketo-transformer/files/8592864/Bold_issue.xml.txt)

This appears to be a recent regression and does not have to do with the markdown module but with `libxmljs.parseHtmlFragment()` post-processsing for media source replacements that happens afterwards, which is why it wasn't caught by the extensive markdown tests.

I've started working on this, and will add a test.

### PR DESCRIPTION
**Pull request by MartijnR**
… when a mediamap is provided, closes #149

The argument provided to `parseHtmlFragment` has to be a valid HTML fragment. If the content contains sibling nodes after markdown transformation, the function silently tries to combine the siblings into a single node (I think) in surprising ways.

It seemed best to add a temporary top level root node before parsing and then ignore that node when serializing it again.

### CODE REVIEW

File: src/transformer.js [hunk 1]
```diff
@@ -498,12 +498,15 @@ function _renderMarkdown(htmlDoc, mediaMap) {
 
             if (original !== rendered) {
                 if (mediaMap != null) {
-                    const fragment = libxmljs.parseHtmlFragment(rendered);
-
-                    rendered = _replaceMediaSources(
-                        fragment,
-                        mediaMap
-                    ).toString(false);
+                    const fragment = libxmljs.parseHtmlFragment(
```
Comment (lognaturel) [inline src/transformer.js:501]: Am I understanding correctly that markdown currently works fine in the absence of any media used by the form but as soon as the form uses media this mangling happens for any label/hint that uses markdown?

I haven't loaded all this context back in to my brain but the two tests above seem odd to me because they're not specifically identifying cases of media usage, it's using a proxy condition that overselects (right?). Probably no action to take now but wanted to mention that this is what jumped out at me.

File: test/forms/bold-media.xml [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+				<data id="Bold_issue" version="1">
+					<note/>
+					<meta>
+						<instanceID/>
+					</meta>
+				</data>
+			</instance>
+			<bind nodeset="/data/note" readonly="true()" type="string"/>
+			<bind jr:preload="uid" nodeset="/data/meta/instanceID" readonly="true()" type="string"/>
+			<instance id="_users" src="jr://file/users.xml"/>
```
Comment (lognaturel) [inline test/forms/bold-media.xml:16]: In continuation of my question above, this is key to the test because it means `mediaMap != null`  is true even though the media file is never used?

File: src/transformer.js (hunk 1 above)
Comment (MartijnR) [reply src/transformer.js:501]: Oh nice find! It turns out mediaMap is actually never `null` (it becomes `{}` without media). I will fix that and then pass a non-empty mediaMap in the tests.

> Am I understanding correctly that markdown currently works fine in the absence of any media used by the form but as soon as the form uses media this mangling happens for any label/hint that uses markdown?

Yes, indeed.

File: src/transformer.js [hunk 3]
```diff
@@ -80,11 +80,15 @@ function transform(survey) {
...
-    );
+    let mediaMap = null;
+
+    if (survey.media) {
+        mediaMap = Object.fromEntries(
+            Object.entries(survey.media).map((entry) =>
+                entry.map(escapeURLPath)
+            )
+        );
+    }
```
Comment (MartijnR) [inline src/transformer.js:91]: Further on in the code some `if()` statements intended to bypass when mediaMap was null or falsy. This fix makes sure mediaMap is `null` if it is not provided.

Interestingly, Enketo Express never provides `survey.media` (so it's `undefined`). This means that this fix alone would fix the bug in Enketo Express.

I found some discussion about why mediaMap replacements are still in enketo-transformer though they are not used by us any more: https://github.com/enketo/enketo-transformer/pull/111

File: test/forms/bold-media.xml (hunk 2 above)
Comment (MartijnR) [reply test/forms/bold-media.xml:16]: I have now explicitly provided a mediaMap in the test. Thanks!

File: src/transformer.js (hunk 1 above)
Comment (MartijnR) [reply src/transformer.js:505]: This bug would surface in case some application does provide `survey.media` when calling `transform`.

File: src/transformer.js (hunk 3 above)
Comment (lognaturel) [reply src/transformer.js:91]: Express is now doing its own media replacement but the `mediaMap` in Transformer was kept for backwards compatibility, is that right? Do we know for sure that it's used and/or should we consider putting it on a deprecation path? I remember this whole area was extremely confusing and any simplification that can be made would have value! It's surprising how many seemingly-unrelated issues have come out of changes in this area.

Comment (MartijnR) [reply src/transformer.js:91]: Yes, I think it was [this comment](https://github.com/enketo/enketo-transformer/pull/111#issuecomment-881085153) by @eyelidlessness:

> It ensures the URLs produced are valid, which means they can also be used consistently in any environment.

It makes sense because it does make enketo-transformer better as a library. I don't have a strong opinion about removing it. The reason for placing enketo-transformer in a separate library was to facilitate development of hybrid mobile apps, and since then it turned out to also be useful for enketo-core development (and enketo-core-performance-monitor). I know that medic ended up not using it (but that may have changed and it likely has), and that ESRI (Survey123) was using it.

File: src/transformer.js [hunk 4]
```diff
@@ -498,12 +502,15 @@ function _renderMarkdown(htmlDoc, mediaMap) {
...
-                    ).toString(false);
+                    const fragment = libxmljs.parseHtmlFragment(
+                        `<div class="temporary-root">${rendered}</div>`
+                    );
+
+                    rendered = _replaceMediaSources(fragment, mediaMap)
+                        .root()
+                        .childNodes()
+                        .map((node) => node.toString(false))
+                        .join('');
```
Comment (eyelidlessness) [inline src/transformer.js:513]: It was unclear to me why this would be a fix, so I did some debugging with the test form. What I found is interesting! This appears to be working around a bug in `libxmljs.parseHtmlFragment`. I looked to find out why this would happen, it appears that internally calls `libxmljs.Document.fromHtml` and hard-codes an `implied: false` option. This solution is fine, but for future reference/context I found this also works:

```js
const doc = libxmljs.Document.fromHtml(rendered);

rendered = replaceMediaSources(doc, mediaMap)
    .get('//body')
    .childNodes()
    .join('');
```

**Review by eyelidlessness — APPROVED** [review]

File: src/transformer.js (hunk 3 above)
Comment (lognaturel) [reply src/transformer.js:91]: Thank you for pulling the context out! Makes sense.
